### ISSUE TITLE
Support a device resource mapping or alias in device resources

### ISSUE THREAD

**Issue by dmocek** [edgexfoundry/device-rest-go#157]
In our implementation/use of EdgeX, we need to use our own device resource (DR) names inside EdgeX.  This is because we ultimately need the data to show up in our NorthBound system using our DR names.  For example, a temperature sensor might send data using a 'temperature' DR name, but in our system the DR name would be more akin to a UUID (e.g. ABC123).  This means we need to convert any use of 'temperature' to 'ABC123'.  We don't want there to be a mix of name and UUID for the DR name in the system as supporting both would be cumbersome, it should be one or the other.  The normalization can be done anywhere, but the typical places are on the way in (device services) and on the way out (NorthBound).  This lets us use only one in EdgeX for everything (e.g. in Kuiper rules).

We need to "normalize" "on the way in" (e.g. device services) because we're adding a non-device service SouthBound route to get data into EdgeX and that route uses UUID's and as stated before it doesn't make sense to support both DR names and UUID's at the same time.  This looks like it won't be a problem on the EdgeX side except for the protocols that require the use of the DR name...notably the REST and MQTT device services.  There is a workaround, which is to configure the device to send data to the REST and MQTT device services using our UUID, but that is not ideal.  A better solution is to support something like an alias that will allow using our UUID as the alias, and if an alias is set, send the data to Core using the alias name as the DR name.

**Comment by iain-anderson** [comment]
Would an app service that re-mapped the name be a possible workaround?

**Comment by dmocek** [comment]
This would mean normalizing "on the way out" and not "on the way in", right?  What I'm looking for, preferably, is to normalize on the way in so all the data has the same type of device resource name while it exists in EdgeX.  This will make processing the data easier as it makes its way through EdgeX (e.g. same Kuiper rules).

**Comment by iain-anderson** [comment]
Ah, okay. For most device services this issue doesn't arise, as the resource name can be chosen freely. So I'd not be in favor of introducing something for aliasing at SDK level. However, in the REST (and MQTT) services the resource name is inferred from the endpoint of the incoming call.

You could implement something in the service so that if device resource A has an attribute `alias` set to `B` then incoming data on `api/v2/{deviceName}/A` would be mapped to device resource B.

I think what we need to get a feel for is how generally applicable a feature this would be. In what way is configuring the device to send data using the UUID as the resource name not ideal?

**Comment by lenny-intel** [comment]
Adding a Resource Alias map to the custom configuration for Device MQTT and Device REST could be an option. The service would check the map when creating a Reading. If there is an alias for the current Resource Name it would use the alias, otherwise it would use the Resource Name from the profile. This would put the map in the service's configuration.toml @dmocek , thoughts?

**Comment by lenny-intel** [comment]
@dmocek , is this still of interest to you? See my last comment. Or can we close it.

**Comment by iain-anderson** [comment]
Moving to icebox as inactive

**Comment by lindseysimple** [comment]
Since no update from 2022, closing this issue.
